version: "3"
# NODERED Stack arm64
# https://nodered.org/docs/getting-started/docker
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - 21880:1880
    networks:
      - prod
    volumes:
    # it seems it doesn't work - `./volumes/node-red` is permanently empty
      - ./nodered-data:/data
      - ./nodered-static:/node-red-static
  aedes:
  # container_name: aedes
    image: moscajs/aedes:latest
    restart: always
    stop_signal: SIGINT
    networks:
      - prod
    command: --config /data/dockerConfig.js
    volumes:
      - ./aedes-data:/data
      - ./aedes_config.js:/data/dockerConfig.js
    ports:
      - '21883:1883'
      - '23000:3000'
      - '24000:4000'
      - '28883:8883'
  mongo:
  # container_name: mongo
    networks:
      - prod
    logging:
      driver: none
    image: mongo:5.0.6-focal
    #image: mvertes/alpine-mongo
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-configdb:/data/configdb
    ports:
      - "27017:27017"
  influxdb:
    image: influxdb:1.8.10
    networks:
      - prod
    volumes:
      - ./influxdb-data:/var/lib/influxdb
      - ./influxdb2-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:5.4.4
    networks:
      - prod
    volumes:
       - ./grafana-data:/var/lib/grafana:rw
    ports:
      - "13000:3000"
  syncthing:
    image: syncthing/syncthing
    #container_name: syncthing
    #hostname: sync-xavier-002
    networks:
      - prod
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data-sync:/var/syncthing
      - ./nextcloud-app/data/admin/files/sync:/var/syncthing/data-sync
    ports:
      - 28384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - prod
    ports:
      - 33306:3306
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud-app:
    image: nextcloud
    networks:
      - prod
    ports:
      - 38080:80
    links:
      - nextcloud-db
    volumes:
      - ./nextcloud-app:/var/www/html
      - ./data-sync/share:/mnt/share
    restart: always
networks:
  prod:
